web server

diff --git a/0x0C-web_server/1-install_nginx_web_server b/0x0C-web_server/1-install_nginx_web_server
--- a/0x0C-web_server/1-install_nginx_web_server
+++ b/0x0C-web_server/1-install_nginx_web_server
@@ -4,5 +4,15 @@
 apt-get -y update
 apt-get -y install nginx
 ufw allow 'Nginx HTTP'
-echo 'Hello World!' > /var/www/html/index.nginx-debian.html
-service nginx start
+echo 'Hello World!' > /var/www/html/index.html
+service nginx restart
+
+# Check if Nginx is installed and configured correctly
+curl -s localhost | grep "Hello World!" > /dev/null
+
+if [ $? -eq 0 ]; then
+    echo "Nginx is installed and serving the correct content."
+else
+    echo "Nginx installation or configuration failed."
+    exit 1
+fi
